---
permalink: intro-family.html 
keywords: storagegrid 
summary: NetApp StorageGRID は、ソフトウェアで定義されるオブジェクトストレージスイートで、パブリック、プライベート、ハイブリッドのマルチクラウド環境での幅広いユースケースに対応します。StorageGRID はAmazon S3 APIをネイティブでサポートし、自動化されたライフサイクル管理などの業界をリードする革新的なテクノロジを提供して、非構造化データを長期にわたってコスト効率よく格納、保護、保持します。 
---
= StorageGRID の詳細をご覧ください
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp StorageGRID は、ソフトウェアで定義されるオブジェクトストレージスイートで、パブリック、プライベート、ハイブリッドのマルチクラウド環境での幅広いユースケースに対応します。StorageGRID はAmazon S3 APIをネイティブでサポートし、自動化されたライフサイクル管理などの業界をリードする革新的なテクノロジを提供して、非構造化データを長期にわたってコスト効率よく格納、保護、保持します。

StorageGRID は、大規模な非構造化データを長期間保管するためのセキュアなストレージを提供します。メタデータベースの統合ライフサイクル管理ポリシーによって、データのライフサイクルを通して最適な保存先が選択されます。コンテンツは適切な場所、適切なタイミングで、適切なストレージ階層に配置されるため、コストを削減できます。

StorageGRID は、地理的に分散した冗長で種類の異なる複数のノードで構成されており、既存および次世代のクライアントアプリケーションと統合できます。



== StorageGRID のメリット

StorageGRIDシステムには次のような利点があります。

* 拡張性にきわめて優れ、使いやすい、地理的に分散された非構造化データリポジトリです。
* Amazon Web Services Simple Storage Service（S3）プロトコルがサポートされます。
* ハイブリッドクラウドの実現：ポリシーベースの情報ライフサイクル管理（ ILM ）を使用して、 Amazon Web Services （ AWS ）や Microsoft Azure などのパブリッククラウドにオブジェクトを格納できます。StorageGRID プラットフォームサービスを使用すると、パブリッククラウドに格納されたオブジェクトのコンテンツレプリケーション、イベント通知、メタデータ検索を行うことができます。
* 柔軟なデータ保護で、データの保持性と可用性を確保レプリケーションと階層型イレイジャーコーディングを使用してデータを保護できます。保存データと転送中データの検証により、長期保持の整合性を確保します。
* 動的なデータライフサイクル管理でストレージコストの管理を支援オブジェクトレベルでデータのライフサイクルを管理する ILM ルールを作成し、データの格納場所、保持性、パフォーマンス、コスト、保持期間を調整できます。
* データストレージの高可用性と一部の管理機能。ロードバランシングの統合により、 StorageGRID リソース全体のデータ負荷を最適化します。
* 複数のストレージテナントアカウントをサポート。システムに格納されているオブジェクトをエンティティごとに分離できます。
* 包括的なアラートシステム、グラフィカルダッシュボード、すべてのノードとサイトの詳細なステータスなど、 StorageGRID システムの健全性を監視するための多数のツールが用意されています。
* ソフトウェアベースまたはハードウェアベースの導入をサポート。StorageGRID は次のいずれかに導入できます。
+
** VMware で実行される仮想マシン。
** Linux ホスト上のコンテナエンジン。
** StorageGRID 社が開発したアプライアンス。
+
*** ストレージアプライアンスはオブジェクトストレージを提供します。
*** サービスアプライアンスは、グリッド管理サービスとロードバランシングサービスを提供します。




* 以下の規制に関連するストレージ要件に準拠しています。
+
** 取引所会員や株式仲買業者を規制するための 17 CFR § 240.17a-4 （ f ）における証券取引委員会（ SEC ）
** 金融業界規制機関（ FINRA ）ルール 4511 （ c ）。 SEC ルール 17a-4 （ f ）の形式とメディア要件は先延ばしになります。
** 商品先物取引を規制するための 17 CFR § 1.31 （ c ） - （ d ）規制の商品先物取引委員会（ CFTC ）


* 無停止のアップグレード処理とメンテナンス処理。アップグレード、拡張、運用停止、メンテナンスの実行中も、コンテンツにアクセスできます。
* フェデレーテッドアイデンティティ管理。ユーザ認証を行うために、 Active Directory 、 OpenLDAP 、または Oracle のディレクトリサービスと統合します。Security Assertion Markup Language 2.0 （ SAML 2.0 ）規格を使用してシングルサインオン（ SSO ）をサポートし、 StorageGRID と Active Directory フェデレーションサービス（ AD FS ）間で認証および許可データをやり取りします。




== 環境でStorageGRID を有効にする方法

に進みます https://docs.netapp.com/us-en/storagegrid-enable/index.html["環境でStorageGRID を有効にする方法"^] を参照して、StorageGRID 環境でアプリケーションをテストして有効にする方法を確認してください。

storagegrid-enable*ドキュメントサイトには、このサイトの製品ドキュメントを拡張した例と料理本が掲載されています。また、StorageGRID を評価して統合するための次のステップについても説明しています。

次のような情報が含まれています。

* 過去および現在のStorageGRID リリースに対応する、検証済みのサードパーティ製ソリューションのリスト。
* 製品機能ガイド。たとえば、これらのガイドには、クラウドストレージプールの作成に必要なすべての情報が記載されています。
* ツールおよびアプリケーションガイド。
* S3の暗号化やS3オブジェクトのロックなど、StorageGRID 機能を使用するためのAPIの例。

