---
settings:
  name: StorageGRID
  search: storagegrid-enable,storagegrid,storagegrid-appliances
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: StorageGRID製品ドキュメント
    url: "/index.html"
